language: java
jdk: openjdk8
services:
  - xvfb    

before_install:
  - sudo apt update
  - sudo apt install openjfx
  - export DISPLAY=:99.0

install: true
script: 
 - mvn test -B --file CaRP/pom.xml
