language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
install: true
script: 
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V --file Wahlverteiler/pom.xml
 - mvn test -B --file Wahlverteiler/pom.xml
